config/routes.rb
Rails.application.routes.draw do
  root to: 'users#index'

  devise_for :users

  resources :users, only: [:show, :index] do
    resources :quits
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :authenticate_user!
end

app/controllers/quits_controller.rb
class QuitsController < ApplicationController
  def new
    @user = User.find params[:user_id]
    @quit = @user.quits.build
  end

  def create
    @user = User.find params[:user_id]
    @quit = Quit.new quit_params
    if @quit.user != current_user
      flash[:alert] = "Can't create/edit a quit for another person!"
      redirect_to root_path
    elsif @quit.save
      flash[:success] = 'Created!'
      redirect_to @quit.user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find params[:user_id]
    @quit = Quit.find params[:id]

  end

  def update
    @quit = Quit.find params[:id]
    if @quit.user != current_user
      flash[:alert] = "Can't create/edit a quit for another person!"
      redirect_to root_path
    elsif @quit.update quit_params
      flash[:success] = 'Updated!'
      redirect_to @quit.user
    else
      render 'edit'
    end
  end

  private

  def quit_params
    params.require(:quit).permit(:text)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lab9</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <div class="header">
      <ul class="nav nav-pills pull-right">
        <% if user_signed_in? %>
        <li><%= link_to 'Log Out', destroy_user_session_path, :method => :delete %></li>
        <% else %>
        <li><%= link_to 'Log In', new_user_session_path %></li>
        <% end %>
        <li><%= link_to 'Users', users_path %></li>
      </ul>
      <h3 class="text-muted">Quitter (Week 9 Lab)</h3>
    </div>
    <% flash.each do |key, value|%>
      <%= content_tag(:div, value, class: "alert alert-#{key}") %>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>

app/views/quits/edit.html.erb
<%= simple_form_for [@user, @quit], html: { class: 'form-horizontal' } do |f| %>
  <%= f.input :text %>
  <%= f.button :submit %>
<% end %>

app/views/quits/new.html.erb
<%= simple_form_for [@user, @quit] do |f| %>
  <%= f.hidden_field :user_id %>
  <%= f.input :text %>
  <%= f.button :submit %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %> <%= link_to '+', new_user_quit_path(user_id: @user) %></h1>
<% @user.quits.each do |quit| %>
  <p><%= quit.text %>  <%= link_to 'Edit', edit_user_quit_path(@user, quit) %></p>
<% end %>